// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagement.Infrastructure.Common;

#nullable disable

namespace ProjectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220102929_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectMemberAssignments.ProjectTaskAssignment", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assignment_date");

                    b.HasKey("TaskId", "MemberId")
                        .HasName("pk_project_task_assignment");

                    b.HasIndex("MemberId");

                    b.ToTable("project_task_assigmnets", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectMembers.ProjectMember", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("member_login");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.ComplexProperty<Dictionary<string, object>>("Status", "ProjectManagement.Domain.ProjectContext.Entities.ProjectMembers.ProjectMember.Status#ProjectMemberStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status_name");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("status_code");
                        });

                    b.HasKey("MemberId")
                        .HasName("pk_project_members");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectOwnershipping.ProjectOwnership", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("ProjectId")
                        .HasName("pk_project_ownerships");

                    b.ToTable("project_ownerships", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectTasks.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Limit")
                        .HasColumnType("smallint")
                        .HasColumnName("members_limit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.ComplexProperty<Dictionary<string, object>>("Information", "ProjectManagement.Domain.ProjectContext.Entities.ProjectTasks.ProjectTask.Information#ProjectTaskInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("title");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("StatusInfo", "ProjectManagement.Domain.ProjectContext.Entities.ProjectTasks.ProjectTask.StatusInfo#ProjectTaskStatusInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Schedule", "ProjectManagement.Domain.ProjectContext.Entities.ProjectTasks.ProjectTask.StatusInfo#ProjectTaskStatusInfo.Schedule#ProjectTaskSchedule", b2 =>
                                {
                                    b2.Property<DateTime?>("Closed")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("closed");

                                    b2.Property<DateTime>("Created")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Status", "ProjectManagement.Domain.ProjectContext.Entities.ProjectTasks.ProjectTask.StatusInfo#ProjectTaskStatusInfo.Status#ProjectTaskStatus", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("value");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_project_tasks");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_tasks", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.ComplexProperty<Dictionary<string, object>>("LifeTime", "ProjectManagement.Domain.ProjectContext.Project.LifeTime#ProjectLifeTime", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("CreatedAt")
                                .HasColumnType("date")
                                .HasColumnName("created_at");

                            b1.Property<DateOnly?>("FinishedAt")
                                .HasColumnType("date")
                                .HasColumnName("finished_at");
                        });

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Domain.UserContext.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("registration_date");

                    b.ComplexProperty<Dictionary<string, object>>("AccountData", "ProjectManagement.Domain.UserContext.User.AccountData#UserAccountData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<string>("Login")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("login");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "ProjectManagement.Domain.UserContext.User.Status#UserStatuses", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status_name");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("status_value");
                        });

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectMemberAssignments.ProjectTaskAssignment", b =>
                {
                    b.HasOne("ProjectManagement.Domain.ProjectContext.Entities.ProjectMembers.ProjectMember", "Member")
                        .WithMany("Assignments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Domain.ProjectContext.Entities.ProjectTasks.ProjectTask", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectMembers.ProjectMember", b =>
                {
                    b.HasOne("ProjectManagement.Domain.ProjectContext.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectOwnershipping.ProjectOwnership", b =>
                {
                    b.HasOne("ProjectManagement.Domain.ProjectContext.Project", null)
                        .WithOne("Ownership")
                        .HasForeignKey("ProjectManagement.Domain.ProjectContext.Entities.ProjectOwnershipping.ProjectOwnership", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectTasks.ProjectTask", b =>
                {
                    b.HasOne("ProjectManagement.Domain.ProjectContext.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectMembers.ProjectMember", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Entities.ProjectTasks.ProjectTask", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProjectContext.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Ownership")
                        .IsRequired();

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
